export default function getAllProducts() {
  // Enhanced product data
  const products = [
    {
      id: "1",
      name: "iPhone 15 Pro Max",
      price: 1199,
      originalPrice: 1299,
      image: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg",
      rating: 4.8,
      reviews: 1250,
      category: "Smartphones",
      isNew: true,
      isOnSale: true,
      stock: 120,
      status: "In Stock",
      sku: "IPH-15PM",
      supplier: "Apple Inc.",
      dateAdded: "2024-09-20",
      sales: 5400,
      trending: true,
      description: "The latest iPhone with advanced camera and A17 Pro chip.",
      images: [],
      updatedAt: "2025-06-30T10:15:00.431Z",
    },
    {
      id: "2",
      name: "Samsung Galaxy S24 Ultra",
      price: 1099,
      image:
        "https://images.pexels.com/photos/1616403/pexels-photo-1616403.jpeg",
      rating: 4.7,
      reviews: 890,
      category: "Smartphones",
      isNew: true,
      stock: 150,
      status: "In Stock",
      sku: "SAM-S24U",
      supplier: "Samsung Electronics",
      dateAdded: "2024-10-10",
      sales: 3200,
      trending: true,
      description: "Premium smartphone with S Pen and cutting-edge display.",
      images: [],
      updatedAt: "2025-06-29T14:30:00.431Z",
    },
    {
      id: "3",
      name: 'iPad Pro 12.9"',
      price: 899,
      originalPrice: 999,
      image:
        "https://images.pexels.com/photos/1334598/pexels-photo-1334598.jpeg",
      rating: 4.9,
      reviews: 567,
      category: "Tablets",
      isOnSale: true,
      stock: 80,
      status: "In Stock",
      sku: "IPD-PRO12",
      supplier: "Apple Inc.",
      dateAdded: "2024-06-15",
      sales: 1800,
      trending: false,
      description: "Powerful tablet with M2 chip for professional use.",
      images: [],
      updatedAt: "2025-06-28T09:45:00.431Z",
    },
    {
      id: "4",
      name: 'MacBook Pro 16"',
      price: 2399,
      image: "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      rating: 4.8,
      reviews: 432,
      category: "Laptops",
      stock: 60,
      status: "In Stock",
      sku: "MBP-16",
      supplier: "Apple Inc.",
      dateAdded: "2024-03-10",
      sales: 1200,
      trending: false,
      description: "High-performance laptop for creators and professionals.",
      images: [],
      updatedAt: "2025-06-27T16:20:00.431Z",
    },
    {
      id: "5",
      name: "AirPods Pro",
      price: 249,
      originalPrice: 279,
      image:
        "https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg",
      rating: 4.6,
      reviews: 2134,
      category: "Audio",
      isOnSale: true,
      stock: 200,
      status: "In Stock",
      sku: "AIR-PPRO",
      supplier: "Apple Inc.",
      dateAdded: "2024-08-05",
      sales: 7800,
      trending: true,
      description: "Wireless earbuds with active noise cancellation.",
      images: [],
      updatedAt: "2025-06-30T12:10:00.431Z",
    },
    {
      id: "6",
      name: "Apple Watch Series 9",
      price: 399,
      image: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg",
      rating: 4.7,
      reviews: 789,
      category: "Accessories",
      isNew: true,
      stock: 90,
      status: "In Stock",
      sku: "AW-S9",
      supplier: "Apple Inc.",
      dateAdded: "2024-09-15",
      sales: 2500,
      trending: true,
      description: "Advanced smartwatch with health and fitness tracking.",
      images: [],
      updatedAt: "2025-06-29T11:00:00.431Z",
    },
    {
      id: "7",
      name: "Google Pixel 8 Pro",
      price: 999,
      image:
        "https://images.pexels.com/photos/1616403/pexels-photo-1616403.jpeg",
      rating: 4.6,
      reviews: 654,
      category: "Smartphones",
      stock: 100,
      status: "In Stock",
      sku: "PIX-8P",
      supplier: "Google LLC",
      dateAdded: "2024-07-20",
      sales: 1900,
      trending: false,
      description:
        "Smartphone with AI-powered features and exceptional camera.",
      images: [],
      updatedAt: "2025-06-28T13:25:00.431Z",
    },
    {
      id: "8",
      name: "Surface Pro 9",
      price: 1299,
      originalPrice: 1399,
      image:
        "https://images.pexels.com/photos/1334598/pexels-photo-1334598.jpeg",
      rating: 4.5,
      reviews: 321,
      category: "Tablets",
      isOnSale: true,
      stock: 70,
      status: "In Stock",
      sku: "SUR-PRO9",
      supplier: "Microsoft Corporation",
      dateAdded: "2024-05-10",
      sales: 1100,
      trending: false,
      description: "Versatile tablet with laptop-level performance.",
      images: [],
      updatedAt: "2025-06-27T15:40:00.431Z",
    },
    {
      id: "9",
      name: "Dell XPS 13",
      price: 1199,
      image: "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      rating: 4.7,
      reviews: 543,
      category: "Laptops",
      stock: 50,
      status: "In Stock",
      sku: "DXPS-13",
      supplier: "Dell Technologies",
      dateAdded: "2024-04-25",
      sales: 1400,
      trending: false,
      description: "Sleek and powerful ultrabook for professionals.",
      images: [],
      updatedAt: "2025-06-28T10:50:00.431Z",
    },
    {
      id: "10",
      name: "OnePlus 12",
      price: 799,
      image: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg",
      rating: 4.5,
      reviews: 432,
      category: "Smartphones",
      isNew: true,
      stock: 110,
      status: "In Stock",
      sku: "OP-12",
      supplier: "OnePlus",
      dateAdded: "2024-11-01",
      sales: 1600,
      trending: true,
      description:
        "Affordable flagship with fast charging and smooth performance.",
      images: [],
      updatedAt: "2025-06-30T08:30:00.431Z",
    },
    {
      id: "11",
      name: "iPad Air",
      price: 599,
      originalPrice: 649,
      image:
        "https://images.pexels.com/photos/1334598/pexels-photo-1334598.jpeg",
      rating: 4.6,
      reviews: 789,
      category: "Tablets",
      isOnSale: true,
      stock: 85,
      status: "In Stock",
      sku: "IPD-AIR",
      supplier: "Apple Inc.",
      dateAdded: "2024-07-10",
      sales: 2100,
      trending: false,
      description: "Lightweight tablet with M1 chip and vibrant display.",
      images: [],
      updatedAt: "2025-06-29T09:15:00.431Z",
    },
    {
      id: "12",
      name: "MacBook Air M3",
      price: 1099,
      image: "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      rating: 4.8,
      reviews: 654,
      category: "Laptops",
      isNew: true,
      stock: 65,
      status: "In Stock",
      sku: "MBA-M3",
      supplier: "Apple Inc.",
      dateAdded: "2024-10-05",
      sales: 1700,
      trending: true,
      description: "Slim laptop with M3 chip for efficient performance.",
      images: [],
      updatedAt: "2025-06-30T14:00:00.431Z",
    },
    {
      id: "13",
      name: "Sony WH-1000XM5",
      price: 399,
      originalPrice: 449,
      image:
        "https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg",
      rating: 4.7,
      reviews: 1123,
      category: "Audio",
      isOnSale: true,
      stock: 130,
      status: "In Stock",
      sku: "SON-WHXM5",
      supplier: "Sony Corporation",
      dateAdded: "2024-06-20",
      sales: 3500,
      trending: true,
      description:
        "Industry-leading noise-canceling headphones with superior sound.",
      images: [],
      updatedAt: "2025-06-29T12:45:00.431Z",
    },
    {
      id: "14",
      name: "Samsung Galaxy Watch 6",
      price: 329,
      image: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg",
      rating: 4.4,
      reviews: 567,
      category: "Accessories",
      stock: 95,
      status: "In Stock",
      sku: "SAM-GW6",
      supplier: "Samsung Electronics",
      dateAdded: "2024-08-15",
      sales: 1400,
      trending: false,
      description: "Smartwatch with comprehensive fitness tracking features.",
      images: [],
      updatedAt: "2025-06-28T11:30:00.431Z",
    },
    {
      id: "15",
      name: "iPhone 14 Pro",
      price: 999,
      originalPrice: 1099,
      image: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg",
      rating: 4.7,
      reviews: 2341,
      category: "Smartphones",
      isOnSale: true,
      stock: 140,
      status: "In Stock",
      sku: "IPH-14P",
      supplier: "Apple Inc.",
      dateAdded: "2024-02-25",
      sales: 6200,
      trending: false,
      description: "Powerful smartphone with dynamic island and A16 chip.",
      images: [],
      updatedAt: "2025-06-27T17:10:00.431Z",
    },
    {
      id: "16",
      name: "Microsoft Surface Laptop 5",
      price: 1299,
      image: "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      rating: 4.5,
      reviews: 432,
      category: "Laptops",
      stock: 55,
      status: "In Stock",
      sku: "SUR-LAP5",
      supplier: "Microsoft Corporation",
      dateAdded: "2024-04-15",
      sales: 1000,
      trending: false,
      description: "Sleek laptop with touchscreen and Windows 11.",
      images: [],
      updatedAt: "2025-06-28T08:20:00.431Z",
    },
    {
      id: "17",
      name: "Bose QuietComfort Earbuds",
      price: 279,
      originalPrice: 329,
      image:
        "https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg",
      rating: 4.6,
      reviews: 876,
      category: "Audio",
      isOnSale: true,
      stock: 160,
      status: "In Stock",
      sku: "BOS-QCE",
      supplier: "Bose Corporation",
      dateAdded: "2024-07-05",
      sales: 2900,
      trending: true,
      description: "Wireless earbuds with superior noise cancellation.",
      images: [],
      updatedAt: "2025-06-29T15:50:00.431Z",
    },
    {
      id: "18",
      name: "Garmin Venu 3",
      price: 449,
      image: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg",
      rating: 4.5,
      reviews: 234,
      category: "Accessories",
      isNew: true,
      stock: 75,
      status: "In Stock",
      sku: "GAR-V3",
      supplier: "Garmin Ltd.",
      dateAdded: "2024-10-20",
      sales: 800,
      trending: true,
      description: "Fitness-focused smartwatch with AMOLED display.",
      images: [],
      updatedAt: "2025-06-30T09:00:00.431Z",
    },
  ];

  return products;
}
