export default function getAllProducts() {
  // Enhanced product data
  const products = [
    {
      id: 1,
      name: "iPhone 15 Pro Max",
      price: 1199,
      originalPrice: 1299,
      category: "phones",
      brand: "Apple",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "The most advanced iPhone ever with titanium design and A17 Pro chip for unprecedented performance.",
      features: [
        "6.7-inch Super Retina XDR display",
        "A17 Pro chip with 6-core GPU",
        "48MP Main camera with 5x zoom",
        "Up to 29 hours video playback",
        "Titanium design",
        "Action Button",
      ],
      inStock: true,
      rating: 4.9,
      reviews: 1250,
      discount: 8,
    },
    {
      id: 2,
      name: "Samsung Galaxy S24 Ultra",
      price: 1099,
      category: "phones",
      brand: "Samsung",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Ultimate Android flagship with S Pen and revolutionary 200MP camera system for professional photography.",
      features: [
        "6.8-inch Dynamic AMOLED 2X",
        "Snapdragon 8 Gen 3 for Galaxy",
        "200MP camera with AI zoom",
        "S Pen included",
        "Titanium frame",
        "Galaxy AI features",
      ],
      inStock: true,
      rating: 4.8,
      reviews: 980,
    },
    {
      id: 3,
      name: "Google Pixel 8 Pro",
      price: 899,
      category: "phones",
      brand: "Google",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Pure Android experience with advanced AI photography features and 7 years of guaranteed updates.",
      features: [
        "6.7-inch LTPO OLED display",
        "Google Tensor G3 chip",
        "50MP Triple camera system",
        "7 years of OS updates",
        "Magic Eraser",
        "Call Screen",
      ],
      inStock: true,
      rating: 4.7,
      reviews: 650,
    },
    {
      id: 4,
      name: "iPad Pro 12.9-inch",
      price: 1099,
      category: "tablets",
      brand: "Apple",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Professional-grade tablet with M2 chip and stunning Liquid Retina XDR display for creative professionals.",
      features: [
        "12.9-inch Liquid Retina XDR",
        "M2 chip with 8-core CPU",
        "12MP Ultra Wide front camera",
        "Apple Pencil (2nd gen) support",
        "Thunderbolt / USB 4",
        "Face ID",
      ],
      inStock: true,
      rating: 4.9,
      reviews: 450,
    },
    {
      id: 5,
      name: "Samsung Galaxy Tab S9+",
      price: 799,
      category: "tablets",
      brand: "Samsung",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Premium Android tablet with S Pen and gorgeous AMOLED display for productivity and entertainment.",
      features: [
        "12.4-inch Dynamic AMOLED 2X",
        "Snapdragon 8 Gen 2 for Galaxy",
        "13MP rear camera",
        "S Pen included",
        "IP68 water resistance",
        "DeX mode",
      ],
      inStock: true,
      rating: 4.6,
      reviews: 320,
    },
    {
      id: 6,
      name: "Sony WH-1000XM5",
      price: 399,
      category: "accessories",
      brand: "Sony",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Industry-leading noise canceling wireless headphones with exceptional sound quality and comfort.",
      features: [
        "30-hour battery life",
        "Multipoint Bluetooth connection",
        "Speak-to-Chat technology",
        "Quick Charge (3 min = 3 hours)",
        "Hi-Res Audio Wireless",
        "Touch controls",
      ],
      inStock: true,
      rating: 4.8,
      reviews: 1999,
    },
    {
      id: 7,
      name: "Apple AirPods Pro (2nd Gen)",
      price: 249,
      category: "accessories",
      brand: "Apple",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Wireless earbuds with active noise cancellation and spatial audio for immersive listening experience.",
      features: [
        "Active Noise Cancellation",
        "Spatial Audio with head tracking",
        "Up to 6 hours listening time",
        "MagSafe charging case",
        "Sweat and water resistant",
        "Touch controls",
      ],
      inStock: true,
      rating: 4.7,
      reviews: 2150,
    },
    {
      id: 8,
      name: "MacBook Pro 14-inch",
      price: 1999,
      category: "laptops",
      brand: "Apple",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Powerful laptop with M3 Pro chip designed for professional workflows and creative tasks.",
      features: [
        "14-inch Liquid Retina XDR display",
        "M3 Pro chip with 11-core CPU",
        "18-hour battery life",
        "Three Thunderbolt 4 ports",
        "1080p FaceTime HD camera",
        "Studio-quality mics",
      ],
      inStock: true,
      rating: 4.9,
      reviews: 780,
    },
    {
      id: 9,
      name: "Dell XPS 13",
      price: 1699,
      category: "laptops",
      brand: "Dell",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Ultra-portable laptop with stunning InfinityEdge display and premium build quality.",
      features: [
        "13.4-inch InfinityEdge display",
        "Intel Core i7-1360P",
        "16GB LPDDR5 RAM",
        "512GB PCIe SSD",
        "Killer Wi-Fi 6E",
        "Windows 11 Pro",
      ],
      inStock: true,
      rating: 4.6,
      reviews: 450,
    },
    {
      id: 10,
      name: "Apple Watch Series 9",
      price: 399,
      category: "wearables",
      brand: "Apple",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Advanced smartwatch with comprehensive health monitoring and innovative Double Tap gesture.",
      features: [
        "Always-On Retina display",
        "S9 SiP with Neural Engine",
        "Double Tap gesture",
        "Up to 18 hours battery life",
        "Blood Oxygen monitoring",
        "ECG app",
      ],
      inStock: true,
      rating: 4.8,
      reviews: 1200,
    },
    {
      id: 11,
      name: "Samsung Galaxy Watch 6",
      price: 329,
      category: "wearables",
      brand: "Samsung",
      image: "/placeholder.svg?height=400&width=400",
      description:
        "Comprehensive health and fitness tracking smartwatch with advanced sleep monitoring.",
      features: [
        "1.3-inch Super AMOLED display",
        "Exynos W930 processor",
        "Advanced sleep tracking",
        "40-hour battery life",
        "Body composition analysis",
        "Wear OS powered by Samsung",
      ],
      inStock: true,
      rating: 4.5,
      reviews: 680,
    },
    {
      id: 12,
      name: "Anker PowerCore 10000",
      price: 29,
      category: "accessories",
      brand: "Anker",
      image:
        "https://gadgetnmusic.com/wp-content/uploads/2023/09/Anker-323-PowerCore-10000mAh-Power-Bank-AA1334H11.jpg",

      description:
        "Compact portable charger with fast charging technology and universal compatibility.",
      features: [
        "10,000mAh capacity",
        "PowerIQ 3.0 technology",
        "Ultra-compact design",
        "Multi-device charging",
        "LED power indicator",
        "18-month warranty",
      ],
      inStock: true,
      rating: 4.7,
      reviews: 3200,
    },
   
  ];

  return products;
}
